# Generated by Django 2.2.7 on 2020-05-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0002_auto_20200505_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('dob', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('contacno', models.CharField(default='1', max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('skill', models.CharField(max_length=20)),
                ('payment', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
