# Generated by Django 2.2.7 on 2020-05-05 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0003_user_tb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_tb',
            old_name='contacno',
            new_name='contactno',
        ),
    ]
