# Generated by Django 2.2.7 on 2020-05-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0005_admin_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='educator_tb',
            name='status',
            field=models.CharField(default='1', max_length=20),
        ),
    ]
