# Generated by Django 2.2.7 on 2020-05-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0006_educator_tb_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='time_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='educator_tb',
            name='availabletime',
            field=models.ForeignKey(default='1', on_delete='CASCADE', to='siteadmin.time_tb'),
        ),
    ]
