# Generated by Django 2.2.7 on 2020-05-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0007_auto_20200508_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='skill_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='educator_tb',
            name='skills',
            field=models.ForeignKey(default='1', on_delete='CASCADE', to='siteadmin.skill_tb'),
        ),
        migrations.AlterField(
            model_name='user_tb',
            name='skill',
            field=models.ForeignKey(default='1', on_delete='CASCADE', to='siteadmin.skill_tb'),
        ),
    ]
