# Generated by Django 2.2.7 on 2020-05-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0008_auto_20200510_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educator_tb',
            name='availabletime',
            field=models.FileField(default='1', max_length=201, upload_to=''),
        ),
    ]
