# Generated by Django 2.2.7 on 2020-05-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0009_auto_20200510_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educator_tb',
            name='availabletime',
            field=models.ForeignKey(default='1', on_delete='CASCADE', to='siteadmin.time_tb'),
        ),
    ]
