# Generated by Django 2.2.7 on 2020-05-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0010_auto_20200510_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='accept_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactno', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('payment', models.CharField(max_length=20)),
                ('educatorid', models.ForeignKey(on_delete='CASCADE', to='siteadmin.educator_tb')),
                ('skillid', models.ForeignKey(on_delete='CASCADE', to='siteadmin.skill_tb')),
                ('userid', models.ForeignKey(on_delete='CASCADE', to='siteadmin.user_tb')),
            ],
        ),
    ]
