# Generated by Django 2.2.7 on 2020-05-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0016_auto_20200510_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_tb',
            name='status',
            field=models.CharField(default='1', max_length=20),
        ),
    ]
