# Generated by Django 2.2.7 on 2020-05-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0018_auto_20200510_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='pay_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalamount', models.CharField(max_length=20)),
                ('totalhours', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('educatorid', models.ForeignKey(on_delete='CASCADE', to='siteadmin.educator_tb')),
                ('userid', models.ForeignKey(on_delete='CASCADE', to='siteadmin.user_tb')),
            ],
        ),
    ]
