# Generated by Django 2.2.7 on 2020-05-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0019_pay_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='accept_tb',
            name='status',
            field=models.CharField(default='1', max_length=20),
        ),
    ]
