# Generated by Django 2.2.7 on 2020-05-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0021_accept_tb_timeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay_tb',
            name='timid',
            field=models.ForeignKey(default='1', on_delete='CASCADE', to='siteadmin.time_tb'),
        ),
    ]
