# Generated by Django 2.2.7 on 2020-05-12 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0023_pay_tb_acceptid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay_tb',
            name='acceptid',
        ),
    ]
