# Generated by Django 2.2.7 on 2020-05-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0024_remove_pay_tb_acceptid'),
    ]

    operations = [
        migrations.AddField(
            model_name='accept_tb',
            name='time',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='pay_tb',
            name='time',
            field=models.CharField(default='1', max_length=20),
        ),
    ]
